name: CI - Checkout

on:
  push:
    tags: ["checkout/v*"]

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci-build-push.yml
    with:
      service: checkout
      ecr_repository: gleamgoods/checkout
    secrets: inherit
