name: CI - Cart

on:
  push:
    branches: [main]
    paths: [cart/**]

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci-build-push.yml
    with:
      service: cart
      ecr_repository: gleamgoods/cart
    secrets: inherit
