name: CI - Catalog

on:
  push:
    tags: ["catalog/v*"]

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci-build-push.yml
    with:
      service: catalog
      ecr_repository: gleamgoods/catalog
    secrets: inherit
