name: CI - Orders

on:
  push:
    tags: ["orders/v*"]

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci-build-push.yml
    with:
      service: orders
      ecr_repository: gleamgoods/orders
    secrets: inherit
